server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: scaa-service
          uri: lb://scaa-service
          predicates:
            - Path=/scaa-service/**
        - id: ass-cache
          uri: lb://ass-cache-service
          predicates:
            - Path=/ass-cache-service/**
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}


