spring:
  application:
    name: ass-cache-service
server:
  servlet:
    context-path: /ass-cache-service
  port: 8082

eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka/
